add setuptools to host requirements for conda packages that need it (#4582)
@caryr35 pointed out to me this morning that `cugraph`'s nightly CI is failing. All `conda-python-build` jobs are failing like this, when building `nx-cugraph`

> ModuleNotFoundError: No module named 'setuptools'
> ...
> ValueError: Could not import build backend specified in pyproject.toml's tool.rapids-build-backend table. Make sure you specified the right optional dependency in your build-system.requires entry for rapids-build-backend.

([build link](https://github.com/rapidsai/cugraph/actions/runs/10176436224/job/28166520972))

**suspected root cause:**  `nx-cugraph` uses `setuptools.build_meta`, but `setuptools` isn't present in the conda build environment

## Notes for Reviewers

### Why is this targeting `branch-24.08`?

Looks like CI is failing there too: https://github.com/rapidsai/cugraph/actions/runs/10183681336/job/28171285190

### Why is this just breaking now?

I suspect that prior to this we were getting `setuptools` because it was a transitive dependency of one of `nx-cugraph`'s other build/host dependencies.

### How could we prevent stuff like this in the future?

We could add support for updating conda recipe files in `rapids-dependency-file-generator` (https://github.com/rapidsai/dependency-file-generator/issues/7).

`setuptools` was correctly added as a build dependency in `pyproject.toml` files here (automatically, via `dependencies.yaml` + `rapids-dependency-file-generator`), but the conda recipe `meta.yaml` files were missed.

Authors:
  - James Lamb (https://github.com/jameslamb)

Approvers:
  - Alex Barghi (https://github.com/alexbarghi-nv)
  - Bradley Dice (https://github.com/bdice)
  - Rick Ratzel (https://github.com/rlratzel)

URL: https://github.com/rapidsai/cugraph/pull/4582